export const euCountries = [
  {"isoCode": "AT", "name": "Austria"},
  {"isoCode": "BE", "name": "Belgium"},
  {"isoCode": "BG", "name": "Bulgaria"},
  {"isoCode": "HR", "name": "Croatia"},
  {"isoCode": "CY", "name": "Cyprus"},
  {"isoCode": "CZ", "name": "Czech Republic"},
  {"isoCode": "DK", "name": "Denmark"},
  {"isoCode": "EE", "name": "Estonia"},
  {"isoCode": "FI", "name": "Finland"},
  {"isoCode": "FR", "name": "France"},
  {"isoCode": "DE", "name": "Germany"},
  {"isoCode": "GR", "name": "Greece"},
  {"isoCode": "HU", "name": "Hungary"},
  {"isoCode": "IE", "name": "Ireland, Republic of (EIRE)"},
  {"isoCode": "IT", "name": "Italy"},
  {"isoCode": "LV", "name": "Latvia"},
  {"isoCode": "LT", "name": "Lithuania"},
  {"isoCode": "LU", "name": "Luxembourg"},
  {"isoCode": "MT", "name": "Malta"},
  {"isoCode": "NL", "name": "Netherlands"},
  {"isoCode": "PL", "name": "Poland"},
  {"isoCode": "PT", "name": "Portugal"},
  {"isoCode": "RO", "name": "Romania"},
  {"isoCode": "SK", "name": "Slovakia"},
  {"isoCode": "SI", "name": "Slovenia"},
  {"isoCode": "ES", "name": "Spain"},
  {"isoCode": "SE", "name": "Sweden"},
  {"isoCode": "GB", "name": "United Kingdom (Great Britain)"},
  // fake countries for testing purposes
  {"isoCode": "BO", "name": "Borduria"},
]
