spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.borduria.eu:8080/realms/eFTI_BO

server:
  port: 8070

gate:
  minSleep: 1000
  maxSleep: 2000
  gateBaseUrl: http://localhost:8880
  platformBaseUrl: http://localhost:${server.port}
  gateSuperApiKey: SuperSecretSecret123
  owner: acme
  cda_path: classpath:cda/
  gate: borduria
  ap:
    url: http://efti.platform.acme.com:81/domibus/services/wsplugin
    username: acme_service_account
    password: Azerty59*1234567

mock:
  badRequestPercentage: 0.0f
  gaussWaitingTime:
    average: 10
    standardDeviation: 5
    isActiveForIdentifierRequestTimer: false
    isTimerActiveForIdentifierResponse: false
  identifierReponseGoodResponse:
    description: description
    status: 200
  identifierReponseBadResponse:
    description: bad gateway
    status: 404


