spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: efti-platform
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics

gate:
  restApiBaseUrl: http://localhost:83/api/platform
