spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.listenbourg.eu:8080/realms/eFTI_LI

server:
  port: 8072

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: umbrellainc
  gateBaseUrl: http://localhost:8881
  platformBaseUrl: http://localhost:${server.port}
  gateSuperApiKey: SuperSecretSecret123
  cda_path: classpath:cda/
  gate: listenbourg
  ap:
    url: http://efti.platform.umbrellainc.com:81/domibus/services/wsplugin
    username: umbrellacorporation_service_account
    password: Azerty59*1234567

