spring:
  rabbitmq:
    password: bo
    username: bo
    virtual-host: bo
  datasource:
    control:
      liquibase:
        default-schema: eftibo
    identifiers:
      liquibase:
        default-schema: eftibo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.borduria.eu:8080/realms/eFTI_BO
  jpa:
    properties:
      hibernate:
        control_schema: "eftibo"
        identifiers_schema: "eftibo"

gate:
  owner: borduria
  country: BO
  ap:
    url: https://harmony-borduria:8443/services/wsplugin
    username: borduria_service_account
    password: Azerty59*1234567

