spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  rabbitmq:
    host: efti-rabbitmq
    listener:
      default-requeue-rejected: false
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
        concurrency: 10
    port: 5672
    queues:
      eftiKeySendMessage: EFTI
      eftiSendMessageExchange: efti.send-message.exchange
      eftiReceiveMessageExchange: efti.receive-message.exchange
      eftiSendMessageQueue: efti.send-messages.q
      eftiReceiveMessageQueue: efti.receive-messages.q
      messageSendDeadLetterQueue: message-send-dead-letter-queue
      messageReceiveDeadLetterQueue: message-receive-dead-letter-queue
  application:
    name: efti-gate
  datasource:
    control:
      jdbc-url: jdbc:postgresql://efti-psql:5432/efti
      url: jdbc:postgresql://efti-psql:5432/efti
      username: efti
      password: ${EFTI_POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.gate.changelog-master.xml
    identifiers:
      jdbc-url: jdbc:postgresql://efti-psql-meta:5432/efti
      url: jdbc:postgresql://efti-psql-meta:5432/efti
      username: root
      password: ${EFTI_META_POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.identifiers.changelog-master.xml
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8880

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

batch:
  update:
    cron: "0 */1 * ? * *"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    enabled: true

efti:
  control:
    pending:
      timeout: 60

