services:
  harmony:
    image: niis/harmony-ap:2.5.0
    depends_on:
      harmony-db:
        condition: service_started
    environment:
      - DB_HOST=harmony-db
      - DB_SCHEMA=harmony_ap
      - DB_PASSWORD=dbpassword
      - ADMIN_PASSWORD=Secret
      - USE_DYNAMIC_DISCOVERY=false
      - PARTY_NAME=${COMPOSE_PROJECT_NAME}
      - SECURITY_KEYSTORE_PASSWORD=changeit
      - SECURITY_TRUSTSTORE_PASSWORD=changeit
      - TLS_KEYSTORE_PASSWORD=changeit
      - TLS_TRUSTSTORE_PASSWORD=changeit
      - SERVER_FQDN=${COMPOSE_PROJECT_NAME}-harmony-1
    volumes:
      - ap_data_gate:/var/opt/harmony-ap
      - ./harmony/gate-ws-plugin.properties:/var/opt/harmony-ap/etc/plugins/config/ws-plugin.properties
      - ./harmony/gate-ws-plugin.properties:/opt/harmony-ap/plugins/config/ws-plugin.properties
      - ./harmony/gate-ws-plugin.properties:/opt/harmony-ap/plugins/ws-plugin.properties
    restart: on-failure
    mem_limit: 1500m
    user: "root:root"

  harmony-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=harmony_ap
      - MYSQL_USER=harmony_ap
      - MYSQL_PASSWORD=dbpassword
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    volumes:
      - db_data_gate:/var/lib/mysql
    restart: on-failure
    mem_limit: 2g

  efti-rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/rabbitmq-defs.json:/etc/rabbitmq/definitions.json
    restart: on-failure

  efti-gate:
    build:
      context: ../
      dockerfile: ./deploy/gate/Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8880/actuator/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      - efti-psql
      - efti-rabbitmq
    environment:
      - OWNER=${COMPOSE_PROJECT_NAME}
      - COUNTRY=${COMPOSE_PROJECT_NAME}
      - ADMIN_API_KEY=an7EL5JR2ThDnXRbvJd7
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  authority-app:
    build:
      context: ../
      dockerfile: ./deploy/authority-app/Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      authority-psql:
        condition: service_started
      efti-gate:
        condition: service_healthy
    environment:
      - GATE-NAME=${COMPOSE_PROJECT_NAME}
      - ADMIN_API_KEY=an7EL5JR2ThDnXRbvJd7
      - AUTHORITY-ID=${COMPOSE_PROJECT_NAME}-authority
    restart: on-failure

  efti-platform:
    build:
      context: ../
      dockerfile: ./deploy/platform/Dockerfile
    profiles: [ "platform" ]
    depends_on:
      - efti-psql
    environment:
      - GATE=${COMPOSE_PROJECT_NAME}
      - ADMIN_API_KEY=an7EL5JR2ThDnXRbvJd7
    restart: on-failure

  efti-psql:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: efti
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - efti_psql:/var/lib/postgresql/data
    restart: on-failure

  efti-psql-meta:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: efti
    volumes:
      - ./sql-meta:/docker-entrypoint-initdb.d
      - efti_psql_meta:/var/lib/postgresql/data
    restart: on-failure

  authority-psql:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authorityapp
    volumes:
      - authority_psql:/var/lib/postgresql/data
    restart: on-failure

  harmony-setup-util:
    build: ./harmony-utils
    depends_on:
      harmony:
        condition: service_started
    environment:
      - HARMONY_USERNAME=harmony
      - HARMONY_PASSWORD=Secret
      - PLUGIN_USER_PASSWORD=Azerty59*1234567
      - KEYSTORE_PASSWORD=changeit
      - TRUSTSTORE_PASSWORD=changeit
      - TLS_KEYSTORE_PASSWORD=changeit
      - TLS_TRUSTSTORE_PASSWORD=changeit
      - HARMONY_GATE_SERVICE_NAME=${COMPOSE_PROJECT_NAME}-harmony-1
      - HARMONY_GATE_PARTY_NAME=${COMPOSE_PROJECT_NAME}
      - HARMONY_SERVICE_PORT=8443
      - PYTHONUNBUFFERED=1


volumes:
  ap_data_gate:
  db_data_gate:
  efti_psql:
  efti_psql_meta:
  authority_psql:
