spring:
  rabbitmq:
    password: bo
    username: bo
    virtual-host: bo
  datasource:
    control:
      liquibase:
        default-schema: eftibo
    identifiers:
      liquibase:
        default-schema: eftibo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.eu:8080/realms/eFTI
  jpa:
    properties:
      hibernate:
        control_schema: "eftibo"
        identifiers_schema: "eftibo"

logging:
  config: classpath:logback-dev.xml

gate:
  country: BO
  owner: borduria
  apikey: SuperSecretSecret123
  ap:
    url: https://localhost:9443/services/wsplugin
    username: service_account
    password: Azerty59*1234567
