spring:
  rabbitmq:
    password: ee
    username: ee
    virtual-host: ee
  datasource:
    control:
      liquibase:
        default-schema: eftiee
    identifiers:
      liquibase:
        default-schema: eftiee
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.eu:8080/realms/eFTI
  jpa:
    properties:
      hibernate:
        control_schema: "eftiee"
        identifiers_schema: "eftiee"

gate:
  country: EE
  owner: estonia
  apikey: SuperSecretSecret123
  ap:
    url: https://localhost:8443/services/wsplugin
    username: service_account
    password: Azerty59*1234567
  description: Estonia gate project
server:
  port: 8881
