services:
  platform-ACME:
    image: openjdk:17
    depends_on:
      - keycloak
      - psql
    volumes:
      - ./platform:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar -Dspring.config.location=file:application.yml -Dspring.profiles.active=ACME platform-simulator.jar --port=8070
    ports:
      - "8070:8070"
      - "8893:5005"
    networks:
      efti:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: [ "start-dev", "--import-realm", "-Dkeycloak.profile.feature.upload_scripts=enabled" ]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
      - DEBUG=true
      - DEBUG_PORT=*:8788
    ports:
      - "8080:8080"
      - "8788:8788"
    volumes:
      - ./keycloak/bo-export.json:/opt/keycloak/data/import/bo-export.json
      - ./keycloak/li-export.json:/opt/keycloak/data/import/li-export.json
      - ./keycloak/sy-export.json:/opt/keycloak/data/import/sy-export.json
    networks:
      efti:
        aliases:
          - auth.gate.borduria.eu
          - auth.gate.syldavia.eu
          - auth.gate.listenbourg.eu

  psql:
    image: postgres:15.4
    container_name: reference-gate-shared-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: efti
    ports:
      - "9001:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      efti:

networks:
  efti:
    name: efti-network
    external: true