openapi: 3.0.1
info:
  title: Gate API in Platform
  description: This API is provided by a platform for the gate
  version: 0.1.0

paths:

  /v0/consignments/{datasetId}:
    parameters:
      - in: path
        name: datasetId
        schema:
          type: string
        required: true
      - in: query
        name: subsetId
        description: A set of subset ids. Must not be empty.
        schema:
          type: array
          uniqueItems: true
          items:
            type: string
        required: true
    get:
      operationId: "getConsignmentSubsets"
      responses:
        "200":
          description: Get the given consignment containing only the elements of the requested subsets
          content:
            application/xml:
              schema:
                type: object
                description: consignment element of type SupplyChainConsignment as defined by schema consignment-common.xsd

  /v0/consignments/{datasetId}/follow-up:
    parameters:
      - in: path
        name: datasetId
        schema:
          type: string
        required: true
    post:
      operationId: "postConsignmentFollowup"
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Add a new follow-up message to consignment
