spring:
  rabbitmq:
    password: pass
    username: user
    virtual-host: host
  datasource:
    control:
      liquibase:
        default-schema: efti_schema
    identifiers:
      liquibase:
        default-schema: efti_schema
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.eu:8080/realms/eFTI
  jpa:
    properties:
      hibernate:
        control_schema: "efti_schema"
        identifiers_schema: "efti_schema"

gate:
  owner: ${OWNER}
  country: ${COUNTRY}
  ap:
    url: https://${OWNER}-harmony-gate-1:8443/services/wsplugin
    username: service_account
    password: Azerty59*1234567
