name: "Deploy efti gate with mock services to server"

on: [ push ]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: echos out stuff
        run: echo "${{ secrets.HOST }} a"
      - name: Update build and run the gate application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
