name: Release

on:
  push:
    branches:
      - main # Triggers when code is pushed to the main branch
      - semantic-versioning # TODO remove once it has been developed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest # Runs on an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Semantic Release
        run: npx semantic-release --branches semantic-versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}