name: "eFTI gate code validation workflow"

on:
  pull_request:
    branches:
      - main

jobs:
  maven-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven package
        run: mvn -B package --file implementation/pom.xml

  xml-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        run: sudo apt-get install -y xmlstarlet
      - name: Validate
        run: utils/validate-examples.sh
